version: "3.3"
services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 5235:3000
    volumes:
      - /srv/local/homepage/config:/app/config
      - /var/run/docker.sock:/var/run/docker.sock
