version: "3"

services:
  db:
    image: bitnami/postgresql:latest
    container_name: joplin-db
    volumes:
      - /srv/local/postgres:/var/lib/postgresql/data
    ports:
      - "5232:5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DATABASE}
  app:
    image: joplin/server:latest
    container_name: joplin-server
    depends_on:
      - db
    ports:
      - "5231:8080"
    restart: unless-stopped
    environment:
      - APP_PORT=8080
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=db
