version: "3.4"
services:
  typesense:
    image: typesense/typesense:26.0
    restart: on-failure
    ports:
      - "5236:8108"
    volumes:
      - /srv/local/typesense:/data
    command: "--data-dir /data --api-key=${API_KEY} --enable-cors"
