version: "3"

services:
  app:
    image: joplin/server:latest
    container_name: joplin-server
    ports:
      - "5231:8080"
    restart: unless-stopped
    environment:
      - APP_PORT=8080
      - APP_BASE_URL=${APP_BASE_URL}
      - DB_CLIENT=pg
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DATABASE=${POSTGRES_DATABASE}
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=postgresql
    networks:
      - postgresql_default
networks:
  postgresql_default:
    external: true
